In [1]:
!pip install tweepy

Collecting tweepy
  Downloading tweepy-4.4.0-py2.py3-none-any.whl (65 kB)
Requirement already satisfied: requests<3,>=2.11.1 in c:\programdata\anaconda3\lib\site-packages (from tweepy) (2.26.0)
Requirement already satisfied: requests-oauthlib<2,>=1.0.0 in c:\programdata\anaconda3\lib\site-packages (from tweepy) (1.3.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.11.1->tweepy) (1.26.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.11.1->tweepy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.11.1->tweepy) (3.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.11.1->tweepy) (2021.10.8)
Requirement already satisfied: oauthlib>=3.0.0 in c:\programdata\anaconda3\lib\site-packages (from requests-oauthlib<2,>=1.0.0->tweepy) (3.1.1)
Installing collected packages: tweepy
Successfully installed tweepy-4.4.0

In [9]:
import configparser
config = configparser.ConfigParser(interpolation=None)
print(config.read('config.cfg'))
print(config.sections())

['config.cfg']
['TWITTER']

In [19]:
import requests
import pandas as pd

In [20]:
client = tweepy.Client( bearer_token=config['TWITTER']['BEARER_TOKEN'], 
                        consumer_key=config['TWITTER']['CONSUMER_KEY'], 
                        consumer_secret=config['TWITTER']['CONSUMER_SECRET'], 
                        access_token=config['TWITTER']['ACCESS_TOKEN'], 
                        access_token_secret=config['TWITTER']['ACCESS_SECRET'], 
                        return_type = requests.Response,
                        wait_on_rate_limit=True)

In [26]:
query = 'from:elonmusk -is:retweet'
tweets = client.search_recent_tweets(query=query, 
                                    tweet_fields=['author_id', 'created_at'],
                                     max_results=100)

In [22]:
tweets_dict = tweets.json() 
tweets_data = tweets_dict['data'] 
df = pd.json_normalize(tweets_data)

In [23]:
df

,author_id,text,created_at,id
0,44196397,Maybe something like this https://t.co/PUBLdaewt8,2022-01-20T03:57:33.000Z,1484012192915677184
1,44196397,https://t.co/rTlxHR4zi1,2022-01-20T03:45:25.000Z,1484009139756056583
2,44196397,Frank &amp; Beans https://t.co/xJfuW6HKs4,2022-01-20T03:17:49.000Z,1484002196538671106
3,44196397,@blueskykites @Grimezsz @WholeMarsBlog @SpaceX...,2022-01-19T21:01:55.000Z,1483907599036780557
4,44196397,@hiromichimizuno Same,2022-01-19T18:27:20.000Z,1483868696246468614
...,...,...,...,...
66,44196397,"@cleantechnica Yeah, doesn’t make sense",2022-01-14T04:50:06.000Z,1481851094061891584
67,44196397,@Teslarati @ResidentSponge Almost all input is...,2022-01-13T20:28:08.000Z,1481724767363338246
68,44196397,@askerlee @giffmana Dojo,2022-01-13T20:20:42.000Z,1481722895713898507
69,44196397,@Rainmaker1973 Yup,2022-01-13T13:20:28.000Z,1481617140809613315
70,44196397,@wintonARK Turns out … yes,2022-01-13T13:01:49.000Z,1481612450126614532

In [32]:
query = '#python ruby'
python_tweets = client.search_recent_tweets(query=query, 
                                    tweet_fields=['author_id', 'created_at'],
                                     max_results=100)

In [33]:
tweets_dict = python_tweets.json() 
tweets_data = tweets_dict['data'] 
df = pd.json_normalize(tweets_data) 
df

,id,created_at,author_id,text
0,1484045131942612995,2022-01-20T06:08:26.000Z,4839215822,RT @devops_jobsNET: HIRING: Senior DevOps Engi...
1,1484044061862514688,2022-01-20T06:04:11.000Z,1423655520196435969,RT @devops_jobsNET: HIRING: Senior DevOps Engi...
2,1484044014575882243,2022-01-20T06:03:59.000Z,1221977161231486977,RT @devops_jobsNET: HIRING: Senior DevOps Engi...
3,1484043986775982081,2022-01-20T06:03:53.000Z,1235115115239919616,HIRING: Senior DevOps Engineer / Boston - http...
4,1484042097779003395,2022-01-20T05:56:22.000Z,1398866593237508100,RT @buabaj_: What is your favorite #vscode the...
...,...,...,...,...
95,1483631714539028480,2022-01-19T02:45:39.000Z,1437728609909706753,RT @first_issues: Executable.executeProgram() ...
96,1483631686563041281,2022-01-19T02:45:33.000Z,1078992647933448192,Executable.executeProgram() discards trailing ...
97,1483618878714675212,2022-01-19T01:54:39.000Z,1437728609909706753,RT @first_issues: Search Option for dropdowns....
98,1483618876638339079,2022-01-19T01:54:39.000Z,1337430590241562626,RT @first_issues: Search Option for dropdowns....
99,1483618876223115264,2022-01-19T01:54:39.000Z,1382032616824651777,RT @first_issues: Search Option for dropdowns....